const nodemailer = require("nodemailer");

function renderTemplate(template, variables = {}) {
  const replace = value => String(value || "").replace(/{{\s*([\w]+)\s*}}/g, (_, key) => variables[key] ?? "");
  const subject = replace(template.subject);
  const body = replace(template.body);
  return {
    subject,
    html: template.html ? replace(template.html) : wrapEmailHtml(subject, body),
    text: body
  };
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function bodyToHtml(body) {
  return String(body || "")
    .split(/\n{2,}/)
    .map(block => {
      const html = escapeHtml(block).replace(/\n/g, "<br>");
      return `<p style="margin:0 0 14px;line-height:1.65;color:#374151;font-size:14px">${html}</p>`;
    })
    .join("");
}

function wrapEmailHtml(subject, body) {
  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(subject)}</title>
  </head>
  <body style="margin:0;padding:0;background:#F3F4F6;font-family:Arial,Helvetica,sans-serif;color:#111827">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F3F4F6;padding:24px 12px">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#FFFFFF;border:1px solid #E5E7EB;border-radius:10px;overflow:hidden">
            <tr>
              <td style="background:#111827;color:#FFFFFF;padding:18px 22px">
                <div style="font-size:18px;font-weight:700;letter-spacing:.02em">ONEPWS PVMS</div>
                <div style="font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#FCA5A5;margin-top:3px">Automated Notification</div>
              </td>
            </tr>
            <tr>
              <td style="padding:24px 22px 12px">
                <h1 style="font-size:18px;line-height:1.35;margin:0 0 18px;color:#111827">${escapeHtml(subject)}</h1>
                ${bodyToHtml(body)}
              </td>
            </tr>
            <tr>
              <td style="background:#F9FAFB;border-top:1px solid #E5E7EB;padding:14px 22px;color:#6B7280;font-size:12px;line-height:1.5">
                This email was generated by the PVMS Automation System. Please do not reply directly to this mailbox.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

function createTransporter() {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    throw new Error("Email environment variables are not configured");
  }
  return nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS
    }
  });
}

async function sendEmail({ to, cc, subject, html, text }) {
  const transporter = createTransporter();
  return transporter.sendMail({
    from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
    to,
    cc,
    subject,
    html,
    text
  });
}

module.exports = { renderTemplate, sendEmail };
