const nodemailer = require("nodemailer");

const DEFAULT_PORTAL_URL = "https://pvms.onepws.com";
const ALWAYS_CC = [
  "sarit.jain@onepws.com",
  "ankit.chittora@onepws.com",
  "mukesh.menaria@onepws.com",
  "atal.tripathi@onepws.com",
  "amit.sukhwal@onepws.com",
  "puneet@onepws.com",
  "kanishka@onepws.com",
  "process@onepws.com",
  "jatin.chouhan@onepws.com"
];

function normalizePortalUrl(value) {
  const raw = String(value || process.env.PVMS_PORTAL_URL || process.env.VERCEL_PROJECT_PRODUCTION_URL || process.env.VERCEL_URL || DEFAULT_PORTAL_URL).trim();
  if (!raw) return DEFAULT_PORTAL_URL;
  return /^https?:\/\//i.test(raw) ? raw : `https://${raw}`;
}

function parseAddresses(value) {
  if (!value) return [];
  const list = Array.isArray(value) ? value : String(value).split(/[;,]/);
  return list
    .map(item => String(item || "").trim())
    .filter(Boolean);
}

function uniqueAddresses(...groups) {
  const seen = new Set();
  const result = [];
  groups.flatMap(parseAddresses).forEach(address => {
    const key = address.toLowerCase();
    if (!seen.has(key)) {
      seen.add(key);
      result.push(address);
    }
  });
  return result;
}

function renderTemplate(template, variables = {}) {
  const replace = value => String(value || "").replace(/{{\s*([\w]+)\s*}}/g, (_, key) => variables[key] ?? "");
  const portalUrl = normalizePortalUrl(variables.portalUrl);
  const subject = replace(template.subject);
  const body = replace(template.body);
  const html = template.html
    ? `${replace(template.html)}${portalCtaHtml(portalUrl)}`
    : wrapEmailHtml(subject, body, portalUrl);
  const text = `${body}\n\nPVMS Portal: ${portalUrl}`;
  return {
    subject,
    html,
    text
  };
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function linkifyHtml(value) {
  return String(value || "").replace(/https?:\/\/[^\s<]+/g, (url) => {
    const cleanUrl = url.replace(/[),.;]+$/, "");
    const suffix = url.slice(cleanUrl.length);
    return `<a href="${cleanUrl}" target="_blank" rel="noopener" style="color:#E31E24;text-decoration:none">${cleanUrl}</a>${suffix}`;
  });
}

function bodyToHtml(body) {
  return String(body || "")
    .split(/\n{2,}/)
    .map(block => {
      const html = linkifyHtml(escapeHtml(block)).replace(/\n/g, "<br>");
      return `<p style="margin:0 0 14px;line-height:1.65;color:#374151;font-size:14px">${html}</p>`;
    })
    .join("");
}

function portalCtaHtml(portalUrl) {
  const safeUrl = escapeHtml(normalizePortalUrl(portalUrl));
  return `<div style="margin:18px 0 8px">
    <a href="${safeUrl}" target="_blank" rel="noopener" style="display:inline-block;background:#E31E24;color:#FFFFFF;text-decoration:none;border-radius:6px;padding:10px 14px;font-size:13px;font-weight:700">Open PVMS Portal</a>
  </div>
  <div style="font-size:12px;color:#6B7280;line-height:1.5;margin-bottom:8px">
    Portal Link: <a href="${safeUrl}" target="_blank" rel="noopener" style="color:#E31E24;text-decoration:none">${safeUrl}</a>
  </div>`;
}

function wrapEmailHtml(subject, body, portalUrl) {
  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(subject)}</title>
  </head>
  <body style="margin:0;padding:0;background:#F3F4F6;font-family:Arial,Helvetica,sans-serif;color:#111827">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F3F4F6;padding:24px 12px">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#FFFFFF;border:1px solid #E5E7EB;border-radius:10px;overflow:hidden">
            <tr>
              <td style="background:#111827;color:#FFFFFF;padding:18px 22px">
                <div style="font-size:18px;font-weight:700;letter-spacing:.02em">ONEPWS PVMS</div>
                <div style="font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#FCA5A5;margin-top:3px">Automated Notification</div>
              </td>
            </tr>
            <tr>
              <td style="padding:24px 22px 12px">
                <h1 style="font-size:18px;line-height:1.35;margin:0 0 18px;color:#111827">${escapeHtml(subject)}</h1>
                ${bodyToHtml(body)}
                ${portalCtaHtml(portalUrl)}
              </td>
            </tr>
            <tr>
              <td style="background:#F9FAFB;border-top:1px solid #E5E7EB;padding:14px 22px;color:#6B7280;font-size:12px;line-height:1.5">
                This email was generated by the PVMS Automation System.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

function createTransporter() {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    throw new Error("Email environment variables are not configured");
  }
  return nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS
    }
  });
}

async function sendEmail({ to, cc, subject, html, text, skipCc }) {
  const transporter = createTransporter();
  const toList = uniqueAddresses(to);
  const ccList = skipCc
    ? uniqueAddresses(cc).filter(address => !toList.some(item => item.toLowerCase() === address.toLowerCase()))
    : uniqueAddresses(cc, ALWAYS_CC).filter(address => !toList.some(item => item.toLowerCase() === address.toLowerCase()));
  return transporter.sendMail({
    from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
    to: toList,
    cc: ccList.length ? ccList : undefined,
    subject,
    html,
    text
  });
}

module.exports = { renderTemplate, sendEmail, normalizePortalUrl, ALWAYS_CC };
